// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SeleniumTracker.Data;

#nullable disable

namespace SeleniumTracker.Migrations
{
    [DbContext(typeof(SeleniumTrackerDbContext))]
    [Migration("20220609165051_seed-data")]
    partial class seeddata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SeleniumTracker.Models.Autotest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("CodelineId")
                        .HasColumnType("int");

                    b.Property<bool>("Failing")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Package")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CodelineId");

                    b.ToTable("Autotests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Class = "Ut in tempore omnis consequuntur magnam",
                            CodelineId = 1,
                            Failing = false,
                            Name = "Quod similique nemo ducimus nihil",
                            Package = "Voluptatem asperiores rerum veniam magni",
                            Priority = 1
                        },
                        new
                        {
                            Id = 2,
                            Class = "Sint modi sit quia voluptas et omnis nostrum non non",
                            CodelineId = 1,
                            Failing = true,
                            Name = "Ipsa quas beatae veniam voluptatem",
                            Package = "Libero vel quisquam quae et voluptatibus non",
                            Priority = 2
                        },
                        new
                        {
                            Id = 3,
                            Class = "Aut qui omnis est expedita",
                            CodelineId = 1,
                            Failing = true,
                            Name = "Et provident saepe aperiam ducimus autem officia tenetur",
                            Package = "Ducimus possimus iste et eveniet aliquam sed quibusdam repellendus",
                            Priority = 2
                        },
                        new
                        {
                            Id = 4,
                            Class = "In voluptatem pariatur quia rerum porro dolorum",
                            CodelineId = 1,
                            Failing = false,
                            Name = "Ut et eum eum vel",
                            Package = "Odit nulla aliquam tempore at",
                            Priority = 2
                        },
                        new
                        {
                            Id = 5,
                            Class = "Dolore et ipsam et a ut",
                            CodelineId = 1,
                            Failing = true,
                            Name = "Possimus et ex magnam et deleniti assumenda quae voluptas officiis",
                            Package = "Distinctio repudiandae molestias ipsa et est",
                            Priority = 1
                        },
                        new
                        {
                            Id = 6,
                            Class = "Illo non rerum consequatur et asperiores est dolor a",
                            CodelineId = 1,
                            Failing = true,
                            Name = "Porro vitae sunt enim qui architecto vitae et",
                            Package = "Libero facilis natus ut alias rerum",
                            Priority = 2
                        },
                        new
                        {
                            Id = 7,
                            Class = "Maxime nemo non non qui",
                            CodelineId = 1,
                            Failing = false,
                            Name = "Aut id vero ipsa voluptatum omnis praesentium repudiandae",
                            Package = "Qui excepturi nesciunt esse cumque amet accusamus veritatis praesentium",
                            Priority = 2
                        },
                        new
                        {
                            Id = 8,
                            Class = "Inventore aut repellat nemo rem enim quibusdam et dolores",
                            CodelineId = 1,
                            Failing = true,
                            Name = "Quia consequatur doloremque velit sed itaque",
                            Package = "Nihil quam harum itaque facilis eos aut eius quia",
                            Priority = 2
                        },
                        new
                        {
                            Id = 9,
                            Class = "Similique animi nam ipsum placeat eum modi saepe eum",
                            CodelineId = 1,
                            Failing = true,
                            Name = "Quas id qui beatae amet beatae velit sit",
                            Package = "Laudantium tenetur maiores recusandae aspernatur consectetur qui tenetur",
                            Priority = 2
                        },
                        new
                        {
                            Id = 10,
                            Class = "Laborum nemo soluta sunt pariatur facere laudantium aut eligendi",
                            CodelineId = 1,
                            Failing = false,
                            Name = "Temporibus eligendi omnis molestias commodi perspiciatis nostrum nihil repellat non",
                            Package = "Maiores quo in dolores placeat qui",
                            Priority = 2
                        },
                        new
                        {
                            Id = 11,
                            Class = "Ut nam sit pariatur et culpa recusandae tempore",
                            CodelineId = 1,
                            Failing = true,
                            Name = "Aut corrupti debitis esse asperiores blanditiis est quod",
                            Package = "Placeat qui dolorem et dolores rerum in dolorum non eos",
                            Priority = 2
                        },
                        new
                        {
                            Id = 12,
                            Class = "Fuga quos debitis cumque sit alias",
                            CodelineId = 1,
                            Failing = false,
                            Name = "Et possimus eveniet voluptas et et repellendus voluptas cum",
                            Package = "Exercitationem hic sed corrupti et quia ipsum et voluptas modi",
                            Priority = 1
                        },
                        new
                        {
                            Id = 13,
                            Class = "Ipsam consequatur porro et perspiciatis ab rem enim",
                            CodelineId = 1,
                            Failing = true,
                            Name = "Rem fugit nobis exercitationem ut in suscipit fuga distinctio",
                            Package = "Unde impedit occaecati facere reprehenderit qui quos illo dignissimos vel",
                            Priority = 0
                        },
                        new
                        {
                            Id = 14,
                            Class = "Eos nobis ipsam molestiae ab",
                            CodelineId = 1,
                            Failing = true,
                            Name = "Sint iure sapiente velit consectetur dignissimos ratione",
                            Package = "Ullam odit earum velit et",
                            Priority = 0
                        },
                        new
                        {
                            Id = 15,
                            Class = "Sapiente necessitatibus officia ut",
                            CodelineId = 1,
                            Failing = true,
                            Name = "Quidem deserunt autem reiciendis voluptates voluptate",
                            Package = "Sunt suscipit sed voluptatem",
                            Priority = 0
                        });
                });

            modelBuilder.Entity("SeleniumTracker.Models.Codeline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Codelines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "14.12"
                        });
                });

            modelBuilder.Entity("SeleniumTracker.Models.Failure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AutotestId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValue(new DateTime(2022, 6, 9, 18, 50, 51, 448, DateTimeKind.Local).AddTicks(463));

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AutotestId");

                    b.ToTable("Failures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AutotestId = 1,
                            Date = new DateTime(2022, 6, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Details = "Nobis totam odio et aut deleniti excepturi sit rem"
                        },
                        new
                        {
                            Id = 2,
                            AutotestId = 2,
                            Date = new DateTime(2022, 6, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Details = "Fugit quos aut ea ut dolorem illum et officia iste"
                        },
                        new
                        {
                            Id = 3,
                            AutotestId = 3,
                            Date = new DateTime(2022, 6, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Details = "Voluptatem alias vero et nam modi alias tempore"
                        },
                        new
                        {
                            Id = 4,
                            AutotestId = 4,
                            Date = new DateTime(2022, 6, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Details = "Ratione dolor repellat debitis"
                        },
                        new
                        {
                            Id = 5,
                            AutotestId = 5,
                            Date = new DateTime(2022, 6, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Details = "Eum repudiandae porro aut molestiae magnam"
                        },
                        new
                        {
                            Id = 6,
                            AutotestId = 6,
                            Date = new DateTime(2022, 6, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Details = "Laborum velit ducimus praesentium maxime quas debitis optio nulla"
                        },
                        new
                        {
                            Id = 7,
                            AutotestId = 7,
                            Date = new DateTime(2022, 6, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Details = "Laboriosam sed non iste sed"
                        },
                        new
                        {
                            Id = 8,
                            AutotestId = 8,
                            Date = new DateTime(2022, 6, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Details = "Reprehenderit a earum corporis accusamus repellat laboriosam quisquam blanditiis aut"
                        },
                        new
                        {
                            Id = 9,
                            AutotestId = 9,
                            Date = new DateTime(2022, 6, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Details = "Non mollitia nesciunt mollitia laudantium reiciendis"
                        },
                        new
                        {
                            Id = 10,
                            AutotestId = 10,
                            Date = new DateTime(2022, 6, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Details = "Perspiciatis sed veritatis sed praesentium in"
                        },
                        new
                        {
                            Id = 11,
                            AutotestId = 11,
                            Date = new DateTime(2022, 6, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Details = "Dolores et autem maxime perspiciatis tenetur odit nobis aliquam"
                        },
                        new
                        {
                            Id = 12,
                            AutotestId = 12,
                            Date = new DateTime(2022, 6, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Details = "Aut nemo sit ratione numquam cum et dolores"
                        },
                        new
                        {
                            Id = 13,
                            AutotestId = 13,
                            Date = new DateTime(2022, 6, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Details = "Inventore aliquam consequatur iste non enim voluptas dolores repudiandae necessitatibus"
                        },
                        new
                        {
                            Id = 14,
                            AutotestId = 14,
                            Date = new DateTime(2022, 6, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Details = "Consequatur qui sunt incidunt quia"
                        },
                        new
                        {
                            Id = 15,
                            AutotestId = 15,
                            Date = new DateTime(2022, 6, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Details = "Error qui pariatur ut debitis temporibus vel"
                        });
                });

            modelBuilder.Entity("SeleniumTracker.Models.Resolution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValue(new DateTime(2022, 6, 9, 18, 50, 51, 448, DateTimeKind.Local).AddTicks(1128));

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FailureId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FailureId")
                        .IsUnique();

                    b.ToTable("Resolutions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2022, 6, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Details = "Ullam adipisci exercitationem deleniti",
                            FailureId = 1
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2022, 6, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Details = "Iusto quia enim nemo aut nulla blanditiis nesciunt minima molestiae",
                            FailureId = 2
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2022, 6, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Details = "Cum et incidunt nihil consequuntur dolores",
                            FailureId = 3
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2022, 6, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Details = "Dolores eos ab cupiditate quae qui nam",
                            FailureId = 4
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2022, 6, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Details = "Est consequatur consequuntur doloribus quasi",
                            FailureId = 5
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2022, 6, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Details = "Cum quia quos id et optio sequi",
                            FailureId = 6
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2022, 6, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Details = "Natus placeat doloribus accusantium voluptas illum consectetur",
                            FailureId = 7
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2022, 6, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Details = "Nostrum inventore esse earum praesentium",
                            FailureId = 8
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2022, 6, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Details = "Fugit amet cumque quia numquam hic ab officiis ab quis",
                            FailureId = 9
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2022, 6, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Details = "Molestias accusantium eius rerum expedita optio numquam autem illo accusamus",
                            FailureId = 10
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateTime(2022, 6, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Details = "Modi quo sint id hic quisquam",
                            FailureId = 11
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateTime(2022, 6, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Details = "Est quia nihil possimus reprehenderit veniam",
                            FailureId = 12
                        },
                        new
                        {
                            Id = 13,
                            Date = new DateTime(2022, 6, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Details = "Necessitatibus odio aperiam totam",
                            FailureId = 13
                        },
                        new
                        {
                            Id = 14,
                            Date = new DateTime(2022, 6, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Details = "Quis sed et in",
                            FailureId = 14
                        },
                        new
                        {
                            Id = 15,
                            Date = new DateTime(2022, 6, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            Details = "Ipsam porro voluptate ad aut",
                            FailureId = 15
                        });
                });

            modelBuilder.Entity("SeleniumTracker.Models.TestLinkAnnotation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AutotestId")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GeneralWorkflow")
                        .HasColumnType("int");

                    b.Property<bool>("Ignore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("SpecificWorkflow")
                        .HasColumnType("int");

                    b.Property<string>("TestlinkId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AutotestId")
                        .IsUnique();

                    b.ToTable("TestLinkAnnotations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AutotestId = 1,
                            Comments = "Enim accusamus vitae et enim voluptatem molestias",
                            GeneralWorkflow = 4,
                            Ignore = true,
                            SpecificWorkflow = 2,
                            TestlinkId = "LS14-1000001"
                        },
                        new
                        {
                            Id = 2,
                            AutotestId = 2,
                            Comments = "Iure dolor maiores facere maiores facere est doloribus",
                            GeneralWorkflow = 2,
                            Ignore = true,
                            SpecificWorkflow = 1,
                            TestlinkId = "LS14-1000002"
                        },
                        new
                        {
                            Id = 3,
                            AutotestId = 3,
                            Comments = "Quos omnis tempore neque dolor doloremque impedit",
                            GeneralWorkflow = 3,
                            Ignore = true,
                            SpecificWorkflow = 1,
                            TestlinkId = "LS14-1000003"
                        },
                        new
                        {
                            Id = 4,
                            AutotestId = 4,
                            Comments = "Quia et quia in quos recusandae rerum et et et",
                            GeneralWorkflow = 1,
                            Ignore = true,
                            SpecificWorkflow = 4,
                            TestlinkId = "LS14-1000004"
                        },
                        new
                        {
                            Id = 5,
                            AutotestId = 5,
                            Comments = "Quis deserunt expedita est et non alias dicta laboriosam aliquam",
                            GeneralWorkflow = 1,
                            Ignore = true,
                            SpecificWorkflow = 2,
                            TestlinkId = "LS14-1000005"
                        },
                        new
                        {
                            Id = 6,
                            AutotestId = 6,
                            Comments = "Eveniet corrupti totam est est",
                            GeneralWorkflow = 0,
                            Ignore = false,
                            SpecificWorkflow = 1,
                            TestlinkId = "LS14-1000006"
                        },
                        new
                        {
                            Id = 7,
                            AutotestId = 7,
                            Comments = "Exercitationem ipsa in quisquam eum cupiditate hic aspernatur",
                            GeneralWorkflow = 4,
                            Ignore = true,
                            SpecificWorkflow = 2,
                            TestlinkId = "LS14-1000007"
                        },
                        new
                        {
                            Id = 8,
                            AutotestId = 8,
                            Comments = "Consequatur quasi ut ut ipsam in beatae voluptatem",
                            GeneralWorkflow = 1,
                            Ignore = true,
                            SpecificWorkflow = 0,
                            TestlinkId = "LS14-1000008"
                        },
                        new
                        {
                            Id = 9,
                            AutotestId = 9,
                            Comments = "Qui non ut quis eum similique et sapiente",
                            GeneralWorkflow = 4,
                            Ignore = false,
                            SpecificWorkflow = 3,
                            TestlinkId = "LS14-1000009"
                        },
                        new
                        {
                            Id = 10,
                            AutotestId = 10,
                            Comments = "Dicta consequatur non officiis quo quo rerum maiores rerum tempore",
                            GeneralWorkflow = 1,
                            Ignore = true,
                            SpecificWorkflow = 1,
                            TestlinkId = "LS14-10000010"
                        },
                        new
                        {
                            Id = 11,
                            AutotestId = 11,
                            Comments = "Sit quos sequi accusamus officiis deserunt delectus distinctio nemo",
                            GeneralWorkflow = 3,
                            Ignore = false,
                            SpecificWorkflow = 2,
                            TestlinkId = "LS14-10000011"
                        },
                        new
                        {
                            Id = 12,
                            AutotestId = 12,
                            Comments = "Id similique amet possimus",
                            GeneralWorkflow = 4,
                            Ignore = true,
                            SpecificWorkflow = 1,
                            TestlinkId = "LS14-10000012"
                        },
                        new
                        {
                            Id = 13,
                            AutotestId = 13,
                            Comments = "Itaque aut quaerat consequuntur nihil et vitae facilis quam",
                            GeneralWorkflow = 2,
                            Ignore = true,
                            SpecificWorkflow = 3,
                            TestlinkId = "LS14-10000013"
                        },
                        new
                        {
                            Id = 14,
                            AutotestId = 14,
                            Comments = "Iure quis quia voluptatum laudantium",
                            GeneralWorkflow = 4,
                            Ignore = true,
                            SpecificWorkflow = 4,
                            TestlinkId = "LS14-10000014"
                        },
                        new
                        {
                            Id = 15,
                            AutotestId = 15,
                            Comments = "Vitae illum ipsum ab sed consectetur dolor",
                            GeneralWorkflow = 3,
                            Ignore = true,
                            SpecificWorkflow = 2,
                            TestlinkId = "LS14-10000015"
                        });
                });

            modelBuilder.Entity("SeleniumTracker.Models.Autotest", b =>
                {
                    b.HasOne("SeleniumTracker.Models.Codeline", "Codeline")
                        .WithMany("Autotests")
                        .HasForeignKey("CodelineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Codeline");
                });

            modelBuilder.Entity("SeleniumTracker.Models.Failure", b =>
                {
                    b.HasOne("SeleniumTracker.Models.Autotest", "Autotest")
                        .WithMany("Failures")
                        .HasForeignKey("AutotestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autotest");
                });

            modelBuilder.Entity("SeleniumTracker.Models.Resolution", b =>
                {
                    b.HasOne("SeleniumTracker.Models.Failure", null)
                        .WithOne("Resolution")
                        .HasForeignKey("SeleniumTracker.Models.Resolution", "FailureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SeleniumTracker.Models.TestLinkAnnotation", b =>
                {
                    b.HasOne("SeleniumTracker.Models.Autotest", null)
                        .WithOne("TestLinkAnnotation")
                        .HasForeignKey("SeleniumTracker.Models.TestLinkAnnotation", "AutotestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SeleniumTracker.Models.Autotest", b =>
                {
                    b.Navigation("Failures");

                    b.Navigation("TestLinkAnnotation")
                        .IsRequired();
                });

            modelBuilder.Entity("SeleniumTracker.Models.Codeline", b =>
                {
                    b.Navigation("Autotests");
                });

            modelBuilder.Entity("SeleniumTracker.Models.Failure", b =>
                {
                    b.Navigation("Resolution");
                });
#pragma warning restore 612, 618
        }
    }
}
